return {
        defaultTab = Color3.fromHex("#ffd3f7"),
        background = Color3.fromRGB(41, 36, 40),
        secondaryBackground = Color3.fromRGB(165, 130, 156),
        tertiaryBackground = Color3.fromRGB(255, 211, 247),
        text = Color3.fromRGB(255, 255, 255),
        image = Color3.fromRGB(255,255,255),
        placeholder = Color3.fromRGB(245,245,245),
        close = Color3.fromRGB(255, 255, 255)
}
