return {
        defaultTab = Color3.fromHex("#ff98d6"),
        background = Color3.fromRGB(129, 114, 123),
        secondaryBackground = Color3.fromRGB(144, 85, 120),
        tertiaryBackground = Color3.fromRGB(255, 152, 214),
        text = Color3.fromRGB(255, 255, 255),
        image = Color3.fromRGB(255,255,255),
        placeholder = Color3.fromRGB(255,255,255),
        close = Color3.fromRGB(255, 255, 255)
}
