return {
	defaultTab = Color3.fromHex("#ffd3f7"),
        background = Color3.fromRGB(129, 114, 126),
        secondaryBackground = Color3.fromRGB(154, 132, 150 ),
        tertiaryBackground = Color3.fromRGB(255, 211, 247),
        text = Color3.fromRGB(255, 255, 255),
        image = Color3.fromRGB(255,255,255),
        placeholder = Color3.fromRGB(245,245,245),
        close = Color3.fromRGB(255, 255, 255)
}
